# Generated by Django 4.2.1 on 2023-08-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Task', '0002_task_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='author',
        ),
    ]
