# Generated by Django 4.2.1 on 2023-08-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Task', '0003_rename_user_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
